---
- name: Add a user
  hosts: 192.168.50.76
  gather_facts: false
  connection: telnet
  tasks:
    - name: Add User
      win_user:
        name: ansible
        password: "nov41972"
        state: present
