---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: local
    bluecat_url: https://10.64.198.203/app
    bluecat_configuration_name: "Loblaw_Production"
    bluecat_dns_view: "Corporate"
    address_properties: excludeDHCPRange=true
    validate_certs: no
  tasks:
    - name: Get IP Address 
      include_role: 
        name: bluecat-ipam-rest
      vars: 
        target_hostname: "ansibletest.example.com"
        state: aquire
