---
- hosts: host.Ubuntu1.192.168.50.143
  become: true
  vars:
  tasks:


    - name: Get plex Key
      shell: wget -q -O - https://downloads.plex.tv/plex-keys/PlexSign.key | apt-key add -
  su
    - name: Add plex repo Repo
      copy: content="deb https://downloads.plex.tv/repo/deb public main" dest=/etc/apt/sources.list.d/plexmediaserver.list owne
